# Generated by Django 4.2.26 on 2025-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'metric'],
                'unique_together': {('date', 'metric')},
            },
        ),
    ]
