# Generated by Django 4.2.26 on 2025-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_aggregator', '0003_userprofile_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='selected_addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
