# Generated by Django 4.2.26 on 2025-11-26 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_aggregator', '0010_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('saved_plan', 'Saved plan'), ('updated_addons', 'Updated add-ons'), ('review_submitted', 'Review submitted'), ('viewed_plan', 'Viewed plan'), ('document_added', 'Document added'), ('support_opened', 'Support opened')], max_length=40),
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='due', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
