# Generated by Django 4.2.26 on 2025-12-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_aggregator', '0011_alter_activity_action_billingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(default='Insurance Buddy', max_length=255)),
                ('meta_description', models.TextField(default='Insurance Buddy helps international students compare travel and health insurance plans designed for life in the U.S.')),
                ('meta_image_path', models.CharField(blank=True, default='img/meta-share.png', help_text='Relative path inside static files (e.g., img/meta-share.png) or a full URL.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site metadata',
                'verbose_name_plural': 'Site metadata',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('saved_plan', 'Saved plan'), ('updated_addons', 'Updated add-ons'), ('review_submitted', 'Review submitted'), ('viewed_plan', 'Viewed plan'), ('document_added', 'Document added'), ('support_opened', 'Support opened'), ('billing_updated', 'Billing updated')], max_length=40),
        ),
    ]
