# Generated by Django 4.2.26 on 2025-12-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_aggregator', '0012_sitemetadata_alter_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemetadata',
            name='meta_image_path',
            field=models.CharField(blank=True, default='img/insure-buddy-meta-image.png', help_text='Relative path inside static files (e.g., img/meta-share.png) or a full URL.', max_length=255),
        ),
    ]
